[package]
name = "OxOS"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
panic = "abort"
codegen-units = 1
lto = false
incremental = false

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
