[package]
name = "OxOS"
version = "0.1.0"
edition = "2024"


[dependencies]
bootloader = "0.9"
volatile = "0.2.7"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.5.2"
x86_64 = "0.14.10"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
